### ISSUE TITLE
multiple updates simultanously entered

### ISSUE THREAD

**Issue by mehrdadjg** [mehrdadjg/Scalability-Dolphins#33]

**Comment by bwstaple** [comment]
Ok how does the operational transform result in mixed strings? Does it or is it the nature of the client trying to display input before it being returned from the proxy?

**Comment by AhmedAlK** [comment]
Good point, I realize that the clients likely get the updates in the same order. If so, then the problem might be with the way the characters are shown on screen before the proxy confirms them

**Comment by bwstaple** [comment]
It looks like there is only one point where the "current file" is displayed. It is at the end of performOutgoingUpdate(), so it makes sense that multiple updates might display incorrectly.
Should be fixed by moving the output to performIncomeingUpdates() and performIncomeingUpdate() so the client only displays "approved" updates that have returned from the proxy.

**Comment by bwstaple** [comment]
measure tolerance for firehosing || fix it

**Comment by bwstaple** [comment]
executive decision we are not going to handle multiple inputs anymore

**Comment by bwstaple** [comment]
//	there needs to be a removeUnapprovedUpdate() in here
	public static void performIncomingUpdates(String updates) {
		String[] msgs = Pattern.compile("\\[|,|\\]").split(updates);
		System.out.println(Arrays.toString(msgs));
		int count = msgs.length;
		for(int i = 0; i < count; i++) {
			String msg = msgs[i];
			if(msg.trim().matches("")) {
				continue;
			}
			DocumentUpdate newUpdate = DocumentUpdate.fromString(msg);
			if(newUpdate != null) {
				performIncomingUpdate(newUpdate);
			}
		}
	}
from client.java line 171 ish

**Comment by mehrdadjg** [comment]
#45
